version: '3'
services:
  database:
    container_name: test-ecs
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: test-ecs
      POSTGRES_PASSWORD: test-ecs
      POSTGRES_DB: test-ecs
    ports:
      - "5432:5432"
    command: postgres -c jit=off
    shm_size: 1024mb
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  mailpit:
      container_name: test-ecs-mailpit
      image: axllent/mailpit:v1.9
      ports:
        - "8025:8025"
        - "1025:1025"
