version: '3'
services:
  database:
    container_name: test-ecs
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: test-ecs
      POSTGRES_PASSWORD: test-ecs
      POSTGRES_DB: test-ecs
    ports:
      - "5432:5432"
