# Generated by Django 4.1 on 2022-09-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0008_optional_internal_vote_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='executive_review_required',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
