# Generated by Django 4.1.13 on 2024-12-06 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_submission_current_ctr_form'),
        ('votes', '0009_alter_vote_executive_review_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='ctr_submission_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.ctrsubmissionform'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='submission_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.submissionform'),
        ),
    ]
