# Generated by Django 5.2.14 on 2026-07-15 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_ctrsubmissionform_submission_current_ctr_form'),
        ('meetings', '0017_meeting_meeting_link'),
        ('votes', '0009_alter_vote_executive_review_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='ctr_submission_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.ctrsubmissionform'),
        ),
        migrations.AddField(
            model_name='vote',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.submission'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='submission_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.submissionform'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ctr_submission_form__isnull', True), ('submission_form__isnull', False)), models.Q(('ctr_submission_form__isnull', False), ('submission_form__isnull', True)), _connector='OR'), name='vote_submission_form_xor_ctr_submission_form'),
        ),
    ]
