# Generated by Django 5.2.14 on 2026-07-15 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_ctrsubmissionform_submission_current_ctr_form'),
        ('votes', '0012_alter_vote_submission_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.submission'),
        ),
    ]
