"""
The CTIS document-type whitelist: every `typeCode` the interface delivers, its
label, and the document kind it belongs to.

Generated from the CTR-ECS `ctis_document_type_whitelist` migrations. CTIS
issues a separate code per publication variant of the same document - « (for
publication) », « (not for publication) », « - Extract » - so a code is too
fine-grained to head a group with. FAMILIES folds the variants of one document
kind together and FAMILY_LABELS names it.

Two quirks of the source are corrected here. The migration's
`documentation_name` is not normalised - the same document arrives under two
stems, e.g. SUITABILITY_OF_THE_TRIAL_SITE and
SUITABILITY_OF_THE_CLINICAL_TRIAL_SITES_FACILITIES - so those are folded. And
codes 100, 109, 257 and 365 carry documentation_name STUDY_DESIGN while their
labels read « Sponsor discussion response supporting document »; the label is
trusted, so they form their own family rather than joining Study design.

This is a whitelist, not the CTIS type list. Of the codes below 385, 224 are
absent, and an absent code is one CTIS issues and CTR-ECS did not take - not a
free slot. So a document kind missing from here is not a gap to fill by
guesswork, and a code must be read off the CTIS type list before it is added.

« Authorisation of manufacturing and import » and « QP GMP certification » are
two such kinds. They are reached by their type string instead of by a code -
see PRODUCT_GMP_DOC_TYPE_PREFIXES in ctis_render.
"""

# typeCode -> the label CTIS gives it. Note that a payload's own `type` string
# sometimes drops the « (not for publication) » qualifier this keeps.
TYPES = {
    '1': 'Agreement from another sponsor (for publication)',
    '2': 'Cover letter (not for publication)',
    '3': 'Proof of payment (for publication)',
    '4': 'Low Intervention Justification (for publication)',
    '5': 'Protocol (not for publication)',
    '6': 'Protocol - Extract (for publication)',
    '7': 'Synopsis of the protocol (for publication)',
    '8': 'Data Safety Monitoring Board Charter (for publication)',
    '9': 'Proof of insurance (for publication)',
    '10': 'Financial arrangements',
    '11': 'Suitability of the clinical trial sites facilities (for publication)',
    '12': 'Investigator CV (for publication)',
    '13': 'Suitability of the investigator (for publication)',
    '14': 'Recruitment arrangements (for publication)',
    '15': 'Subject information and informed consent form (for publication)',
    '16': 'Summary of scientific advice (for publication)',
    '19': 'Summary of Product Characteristics (SmPC) (for publication)',
    '23': 'Investigational Medicinal Product Dossier: Safety and Efficacy (for publication)',
    '25': 'Simplified IMPD: Safety and Efficacy (for publication)',
    '29': 'Content labelling of the IMPs (for publication)',
    '30': 'Follow up measures',
    '31': 'Inspection report (not for publication)',
    '32': 'Inspection report (for publication)',
    '33': 'Inspection report: Third country inspectorate (not for publication)',
    '34': 'Union control report (not for publication)',
    '35': 'Union control report (for publication)',
    '36': 'Serious breach report (not for publication)',
    '37': 'Serious breach report (for publication)',
    '41': 'Part II Assessment Report - Final (not for publication)',
    '42': 'Part II Assessment Report - Final (for publication)',
    '44': 'Clinical study report (not for publication)',
    '45': 'Clinical study report (for publication)',
    '46': 'Laypersons summary of results (for publication)',
    '47': 'Summary attachment (for publication)',
    '48': 'Charts - add attachments (for publication)',
    '49': 'Cover letter (for publication)',
    '52': 'Modification Description (for publication)',
    '53': 'Inspection report: Third country inspectorate (for publication)',
    '54': 'Corrective Measure Justification (for publication)',
    '55': 'Agreement from another sponsor - Extract (for publication)',
    '56': 'Justification of the low interventional clinical trial - Extract (for publication)',
    '57': 'Synopsis of the Protocol - Extract (for publication)',
    '58': 'Proof of insurance - Extract (for publication)',
    '59': 'Financial arrangements - Extract',
    '60': 'Suitability of the clinical trial sites facilities - Extract (for publication)',
    '61': 'Investigator CV - Extract (for publication)',
    '62': 'Suitability of the investigator - Extract (for publication)',
    '63': 'Recruitment arrangements - Extract (for publication)',
    '64': 'Subject information and informed consent form - Extract (for publication)',
    '65': 'Summary of scientific advice report - Extract (for publication)',
    '67': 'Investigator Brochure - Extract (for publication)',
    '68': 'Summary of Product Characteristics (SmPC) - Extract (for publication)',
    '73': 'Simplified IMPD - Extract',
    '78': 'Content labelling of the IMPs - Extract (for publication)',
    '79': 'Data safety monitoring Board Charter - Extract (for publication)',
    '80': 'Corrective Measure Withdraw Justification',
    '81': 'Clock Stop Agreement (for publication)',
    '82': 'Part II assessment report - Draft',
    '83': 'Corrective measure revert justification',
    '84': 'Corrective measure investigator opinion',
    '85': 'Corrective measure MSC consultation',
    '86': 'Part I Section 1 Introduction - Draft',
    '88': 'Part I Section 3 Pre clinical Assessment - Draft',
    '89': 'Part I Section 4 Clinical Assessment - Draft',
    '90': 'Part I Section 5 Statistical Methodological Assessment - Draft',
    '91': 'Part I Section 6 Regulatory Assessment - Draft',
    '92': 'Part I Section 7 Conclusion - Draft',
    '95': 'Corrective Measure Request Opinion (for publication)',
    '96': 'Part I Disagreement Justification (for publication)',
    '97': 'Summary of Assessment and Outcome (for publication)',
    '98': 'Additional Information Assessment Conclusion',
    '99': 'MSC Additional Information Assessment Discussion Request',
    '100': 'Sponsor discussion response supporting document',
    '101': 'Supporting information (for publication)',
    '102': 'Plan/Programme for Union controls for Member States',
    '103': 'Summary of results (for publication)',
    '104': 'Protocol (for publication)',
    '106': 'Additional information assessment - Supporting documentation',
    '108': 'Assessment Discussion Request',
    '109': 'Sponsor discussion response supporting document (for publication)',
    '110': 'Corrective measure deliver opinion',
    '111': 'Summary of results (not for publication)',
    '112': 'Corrective measure Sponsor Opinion',
    '200': 'Study design (for publication)',
    '201': 'Revert Decision Supporting documentation (for publication)',
    '210': 'Union Control Supporting documentation',
    '211': 'Union Control Report Supporting documentation',
    '216': 'Unexpected event report (not for publication)',
    '217': 'Unexpected event report (for publication)',
    '218': 'Urgent safety measure report (not for publication)',
    '219': 'Urgent safety measure report (for publication)',
    '251': 'List of Changes (for publication)',
    '254': 'Investigator Brochure',
    '257': 'Sponsor discussion response supporting document',
    '261': 'Additional information assessment - Supporting documentation',
    '262': 'Additional Information Assessment Conclusion',
    '274': 'Part I assessment report except quality - Final (for publication)',
    '277': 'Compliance with national requirements on Data Protection (for publication)',
    '278': 'Compliance with use of Biological samples (for publication)',
    '281': 'Part I Intended Disagreement Justification',
    '308': 'Synopsis of the protocol (not for publication)',
    '309': 'Data Safety Monitoring Board Charter (not for publication)',
    '310': 'Study design (not for publication)',
    '311': 'Summary of scientific advice (not for publication)',
    '313': 'Investigator Brochure (not for publication)',
    '314': 'Summary of Product Characteristics (SmPC) (not for publication)',
    '317': 'Content labelling of the IMPs (not for publication)',
    '318': 'Proof of insurance (not for publication)',
    '319': 'Suitability of the clinical trial sites facilities (not for publication)',
    '320': 'Investigator CV (not for publication)',
    '321': 'Suitability of the investigator (not for publication)',
    '322': 'Recruitment arrangements (not for publication)',
    '323': 'Subject information and informed consent form (not for publication)',
    '324': 'Modification Description (not for publication)',
    '326': 'Proof of payment (not for publication)',
    '327': 'Compliance with national requirements on Data Protection (not for publication)',
    '328': 'Compliance with use of Biological samples (not for publication)',
    '329': 'Low Intervention Justification (not for publication)',
    '330': 'Clock Stop Agreement (not for publication)',
    '331': 'Investigational Medicinal Product Dossier: Safety and Efficacy (not for publication)',
    '332': 'Simplified IMPD: Safety and Efficacy (not for publication)',
    '333': 'Laypersons summary of results (not for publication)',
    '335': 'Supporting document from MS - Non Quality (for publication)',
    '336': 'Agreement from another sponsor (not for publication)',
    '337': 'Protocol - Extract (not for publication)',
    '338': 'Summary attachment (not for publication)',
    '339': 'Charts - add attachments (for publication)',
    '341': 'Corrective Measure Justification (not for publication)',
    '342': 'Agreement from another sponsor - Extract (not for publication)',
    '343': 'Justification of the low interventional clinical trial - Extract (not for publication)',
    '344': 'Synopsis of the Protocol - Extract (not for publication)',
    '345': 'Proof of insurance - Extract (not for publication)',
    '346': 'Suitability of the clinical trial sites facilities - Extract (not for publication)',
    '347': 'Investigator CV - Extract (not for publication)',
    '348': 'Suitability of the investigator - Extract (not for publication)',
    '349': 'Recruitment arrangements - Extract (not for publication)',
    '350': 'Subject information and informed consent form - Extract (not for publication)',
    '351': 'Summary of scientific advice report - Extract (not for publication)',
    '352': 'PIP opinion - Extract (not for publication)',
    '353': 'Investigator Brochure - Extract (not for publication)',
    '354': 'Summary of Product Characteristics (SmPC) - Extract (not for publication)',
    '360': 'Content labelling of the IMPs - Extract (not for publication)',
    '361': 'Data safety monitoring Board Charter - Extract (not for publication)',
    '362': 'Part I Disagreement Justification (not for publication)',
    '363': 'Summary of Assessment and Outcome (not for publication)',
    '364': 'Supporting information (not for publication)',
    '365': 'Sponsor discussion response supporting document (not for publication)',
    '366': 'Part I assessment report except quality - Final (not for publication)',
    '367': 'Revert Decision Supporting documentation (not for publication)',
    '369': 'Supporting document from MS - Non Quality (not for publication)',
    '373': 'List of Changes (not for publication)',
    '375': 'Supporting information withdraw (for publication)',
    '376': 'Supporting information withdraw (not for publication)',
    '377': 'Compliance with national requirements on Data Protection - Extract (for publication)',
    '378': 'Compliance with use of Biological samples - Extract (for publication)',
    '379': 'Compliance with national requirements on Data Protection - Extract (not for publication)',
    '380': 'Compliance with use of Biological samples - Extract (not for publication)',
    '381': 'Study design - Extract (for publication)',
    '382': 'Study design - Extract (not for publication)',
    '384': 'Joint Controllership Agreement',
    '385': 'Privacy Statement',
}

# typeCode -> document kind.
FAMILIES = {
    '1': 'AGREEMENT_FROM_ANOTHER_SPONSOR',
    '2': 'COVER_LETTER',
    '3': 'PROOF_OF_PAYMENT',
    '4': 'LOW_INTERVENTION_JUSTIFICATION',
    '5': 'PROTOCOL',
    '6': 'PROTOCOL',
    '7': 'SYNOPSIS_OF_THE_PROTOCOL',
    '8': 'DATA_SAFETY_MONITORING_BOARD_CHARTER',
    '9': 'PROOF_OF_INSURANCE',
    '10': 'FINANCIAL_ARRANGEMENTS',
    '11': 'SUITABILITY_OF_THE_CLINICAL_TRIAL_SITES_FACILITIES',
    '12': 'INVESTIGATOR_CURRICULUM_VITAE',
    '13': 'SUITABILITY_OF_THE_INVESTIGATOR',
    '14': 'RECRUITMENT_ARRANGEMENTS',
    '15': 'SUBJECT_INFORMATION_AND_INFORMED_CONSENT_FORM',
    '16': 'SUMMARY_OF_SCIENTIFIC_ADVICE',
    '19': 'SUMMARY_OF_PRODUCT_CHARACTERISTICS',
    '23': 'INVESTIGATIONAL_MEDICAL_PRODUCT_DOSSIER_SAFETY_AND_EFFICACY',
    '25': 'SIMPLIFIED_INVESTIGATIONAL_MEDICAL_PRODUCT_DOSSIER_SAFETY_EFFICACY',
    '29': 'CONTENT_LABELLING_OF_THE_IMPS',
    '30': 'FOLLOW_UP_MEASURES',
    '31': 'INSPECTION_REPORT',
    '32': 'INSPECTION_REPORT',
    '33': 'INSPECTION_REPORT_THIRD_COUNTRY_INSPECTORATE',
    '34': 'UNION_CONTROL_REPORT',
    '35': 'UNION_CONTROL_REPORT',
    '36': 'SERIOUS_BREACH_REPORT',
    '37': 'SERIOUS_BREACH_REPORT',
    '41': 'PART2_ASSESSMENT_REPORT_FINAL',
    '42': 'PART2_ASSESSMENT_REPORT_FINAL',
    '44': 'CLINICAL_STUDY_REPORT',
    '45': 'CLINICAL_STUDY_REPORT',
    '46': 'LAYPERSONS_SUMMARY_OF_RESULTS',
    '47': 'SUMMARY_ATTACHMENT',
    '48': 'CHARTS_ADD_ATTACHMENTS',
    '49': 'COVER_LETTER',
    '52': 'DESCRIPTION_OF_MODIFICATION',
    '53': 'INSPECTION_REPORT_THIRD_COUNTRY_INSPECTORATE',
    '54': 'CORRECTIVE_MEASURE_JUSTIFICATION',
    '55': 'AGREEMENT_FROM_ANOTHER_SPONSOR',
    '56': 'LOW_INTERVENTION_JUSTIFICATION',
    '57': 'SYNOPSIS_OF_THE_PROTOCOL',
    '58': 'PROOF_OF_INSURANCE',
    '59': 'FINANCIAL_ARRANGEMENTS',
    '60': 'SUITABILITY_OF_THE_CLINICAL_TRIAL_SITES_FACILITIES',
    '61': 'INVESTIGATOR_CURRICULUM_VITAE',
    '62': 'SUITABILITY_OF_THE_INVESTIGATOR',
    '63': 'RECRUITMENT_ARRANGEMENTS',
    '64': 'SUBJECT_INFORMATION_AND_INFORMED_CONSENT_FORM',
    '65': 'SUMMARY_OF_SCIENTIFIC_ADVICE_REPORT',
    '67': 'INVESTIGATOR_BROCHURE',
    '68': 'SUMMARY_OF_PRODUCT_CHARACTERISTICS',
    '73': 'SIMPLIFIED_INVESTIGATIONAL_MEDICAL_PRODUCT_DOSSIER_SAFETY_EFFICACY',
    '78': 'CONTENT_LABELLING_OF_THE_IMPS',
    '79': 'DATA_SAFETY_MONITORING_BOARD_CHARTER',
    '80': 'CORRECTIVE_MEASUER_WITHDRAW_JUSTIFICATION',
    '81': 'CLOCK_STOP_AGGREMENT',
    '82': 'PART2_ASSESSMENT_REPORT_DRAFT',
    '83': 'CORRECTIVE_MEASURE_REVERT_JUSTIFICATION',
    '84': 'CORRECTIVE_MEASURE_INVESTIGATOR_OPINION',
    '85': 'CORRECTIVE_MEASURE_MSC_CONSULTATION',
    '86': 'PART1_SECTION_1_INTRODUCTION_DRAFT',
    '88': 'PART1_SECTION_3_PRE_CLINICAL_ASSESSMENT_DRAFT',
    '89': 'PARR1_SECTION_4_CLINICAL_ASSESSMENT_DRAFT',
    '90': 'PARR1_SECTION_5_STATISTICAL_METHOLOGICAL_ASSESSMENT_DRAFT',
    '91': 'PARR1_SECTION_6_REGULATORY_ASSESSMENT_DRAFT',
    '92': 'PARR1_SECTION_7_CONCLUSION_DRAFT',
    '95': 'CORRECTIVE_MEASURE_REQUEST',
    '96': 'PART1_DISAGREEMENT_JUSTIFICATION',
    '97': 'SUMMARY_OF_ASSESSMENT_AND_OUTCOME',
    '98': 'ADDITIONAL_ASSESSMENT_CONCLUSION',
    '99': 'MSC_ADDITIONAL_INFORMATION_ASSESSMENT_DISCUSION_REQUEST',
    '100': 'SPONSOR_DISCUSSION_RESPONSE_SUPPORTING_DOCUMENT',
    '101': 'SUPPORTING_INFORMATION',
    '102': 'PLAN_PROGRAMME_FOR_UNION_CONTROLS_FOR_MEMBER_STATES',
    '103': 'SUMMARY_OF_RESULTS',
    '104': 'PROTOCOL',
    '106': 'ADDITIONAL_INFORMATION_ASSESSMENT_SUPPORTING_DOCUMENTATION',
    '108': 'ASSESSMENT_DISCUSION_REQUEST',
    '109': 'SPONSOR_DISCUSSION_RESPONSE_SUPPORTING_DOCUMENT',
    '110': 'CORRECTIVE_MEASURE_DELIVER_OPINION',
    '111': 'SUMMARY_OF_RESULTS',
    '112': 'CORRECTIVE_MEASURE_SPONSOR_OPINION',
    '200': 'STUDY_DESIGN',
    '201': 'REVERT_DECISION_SUPPORTING_DOCUMENTATION',
    '210': 'UNION_CONTROL_SUPPORTING_DOCUMENTATION',
    '211': 'UNION_CONTROL_REPORT_SUPPORTING_DOCUMENTATION',
    '216': 'UNEXPECTED_EVENT_REPORT',
    '217': 'UNEXPECTED_EVENT_REPORT',
    '218': 'URGENT_SAFETY_MEASURE_REPORT',
    '219': 'URGENT_SAFETY_MEASURE_REPORT',
    '251': 'LIST_OF_CHANGES',
    '254': 'INVESTIGATOR_BROCHURE',
    '257': 'SPONSOR_DISCUSSION_RESPONSE_SUPPORTING_DOCUMENT',
    '261': 'ADDITIONAL_INFORMATION_ASSESSMENT_SUPPORTING_DOCUMENTATION',
    '262': 'ADDITIONAL_ASSESSMENT_CONCLUSION',
    '274': 'PART1_ASSESSMENT_REPORT_EXCEPT_QUALITY_FINAL',
    '277': 'COMPLIANCE_WITH_NATIONAL_REQUIREMENTS_ON_DATE_PROTECTION',
    '278': 'COMPLIANCE_WITH_USE_OF_BIOLOGICAL_SAMPLES',
    '281': 'PART1_INTENDED_DISAGREEMENT_JUSTIFICATION',
    '308': 'SYNOPSIS_OF_THE_PROTOCOL',
    '309': 'DATA_SAFETY_MONITORING_BOARD_CHARTER',
    '310': 'STUDY_DESIGN',
    '311': 'SUMMARY_OF_SCIENTIFIC_ADVICE',
    '313': 'INVESTIGATOR_BROCHURE',
    '314': 'SUMMARY_OF_PRODUCT_CHARACTERISTICS',
    '317': 'CONTENT_LABELLING_OF_THE_IMPS',
    '318': 'PROOF_OF_INSURANCE',
    '319': 'SUITABILITY_OF_THE_CLINICAL_TRIAL_SITES_FACILITIES',
    '320': 'INVESTIGATOR_CURRICULUM_VITAE',
    '321': 'SUITABILITY_OF_THE_INVESTIGATOR',
    '322': 'RECRUITMENT_ARRANGEMENTS',
    '323': 'SUBJECT_INFORMATION_AND_INFORMED_CONSENT_FORM',
    '324': 'DESCRIPTION_OF_MODIFICATION',
    '326': 'PROOF_OF_PAYMENT',
    '327': 'COMPLIANCE_WITH_NATIONAL_REQUIREMENTS_ON_DATE_PROTECTION',
    '328': 'COMPLIANCE_WITH_USE_OF_BIOLOGICAL_SAMPLES',
    '329': 'LOW_INTERVENTION_JUSTIFICATION',
    '330': 'CLOCK_STOP_AGGREMENT',
    '331': 'INVESTIGATIONAL_MEDICAL_PRODUCT_DOSSIER_SAFETY_AND_EFFICACY',
    '332': 'SIMPLIFIED_INVESTIGATIONAL_MEDICAL_PRODUCT_DOSSIER_SAFETY_EFFICACY',
    '333': 'LAYPERSONS_SUMMARY_OF_RESULTS',
    '335': 'SUPPORTING_DOCUMENT',
    '336': 'AGREEMENT_FROM_ANOTHER_SPONSOR',
    '337': 'PROTOCOL',
    '338': 'SUMMARY_ATTACHMENT',
    '339': 'CHARTS_ADD_ATTACHMENTS',
    '341': 'CORRECTIVE_MEASURE_JUSTIFICATION',
    '342': 'AGREEMENT_FROM_ANOTHER_SPONSOR',
    '343': 'LOW_INTERVENTION_JUSTIFICATION',
    '344': 'SYNOPSIS_OF_THE_PROTOCOL',
    '345': 'PROOF_OF_INSURANCE',
    '346': 'SUITABILITY_OF_THE_CLINICAL_TRIAL_SITES_FACILITIES',
    '347': 'INVESTIGATOR_CURRICULUM_VITAE',
    '348': 'SUITABILITY_OF_THE_INVESTIGATOR',
    '349': 'RECRUITMENT_ARRANGEMENTS',
    '350': 'SUBJECT_INFORMATION_AND_INFORMED_CONSENT_FORM',
    '351': 'SUMMARY_OF_SCIENTIFIC_ADVICE_REPORT',
    '352': 'PIP_OPINION',
    '353': 'INVESTIGATOR_BROCHURE',
    '354': 'SUMMARY_OF_PRODUCT_CHARACTERISTICS',
    '360': 'CONTENT_LABELLING_OF_THE_IMPS',
    '361': 'DATA_SAFETY_MONITORING_BOARD_CHARTER',
    '362': 'PART1_DISAGREEMENT_JUSTIFICATION',
    '363': 'SUMMARY_OF_ASSESSMENT_AND_OUTCOME',
    '364': 'SUPPORTING_INFORMATION',
    '365': 'SPONSOR_DISCUSSION_RESPONSE_SUPPORTING_DOCUMENT',
    '366': 'PART1_ASSESSMENT_REPORT_EXCEPT_QUALITY_FINAL',
    '367': 'REVERT_DECISION_SUPPORTING_DOCUMENTATION',
    '369': 'SUPPORTING_DOCUMENT',
    '373': 'LIST_OF_CHANGES',
    '375': 'SUPPORTING_INFORMATION_WITHDRAW',
    '376': 'SUPPORTING_INFORMATION_WITHDRAW',
    '377': 'COMPLIANCE_WITH_NATIONAL_REQUIREMENTS_ON_DATE_PROTECTION',
    '378': 'COMPLIANCE_WITH_USE_OF_BIOLOGICAL_SAMPLES',
    '379': 'COMPLIANCE_WITH_NATIONAL_REQUIREMENTS_ON_DATE_PROTECTION',
    '380': 'COMPLIANCE_WITH_USE_OF_BIOLOGICAL_SAMPLES',
    '381': 'STUDY_DESIGN',
    '382': 'STUDY_DESIGN',
    '384': 'JOINT_CONTROLLERSHIP_AGREEMENT',
    '385': 'PRIVACY_STATMENT',
}

# document kind -> the heading it gets.
FAMILY_LABELS = {
    'ADDITIONAL_ASSESSMENT_CONCLUSION': 'Additional Information Assessment Conclusion',
    'ADDITIONAL_INFORMATION_ASSESSMENT_SUPPORTING_DOCUMENTATION': 'Additional information assessment - Supporting documentation',
    'AGREEMENT_FROM_ANOTHER_SPONSOR': 'Agreement from another sponsor',
    'ASSESSMENT_DISCUSION_REQUEST': 'Assessment Discussion Request',
    'CHARTS_ADD_ATTACHMENTS': 'Charts - add attachments',
    'CLINICAL_STUDY_REPORT': 'Clinical study report',
    'CLOCK_STOP_AGGREMENT': 'Clock Stop Agreement',
    'COMPLIANCE_WITH_NATIONAL_REQUIREMENTS_ON_DATE_PROTECTION': 'Compliance with national requirements on Data Protection',
    'COMPLIANCE_WITH_USE_OF_BIOLOGICAL_SAMPLES': 'Compliance with use of Biological samples',
    'CONTENT_LABELLING_OF_THE_IMPS': 'Content labelling of the IMPs',
    'CORRECTIVE_MEASUER_WITHDRAW_JUSTIFICATION': 'Corrective Measure Withdraw Justification',
    'CORRECTIVE_MEASURE_DELIVER_OPINION': 'Corrective measure deliver opinion',
    'CORRECTIVE_MEASURE_INVESTIGATOR_OPINION': 'Corrective measure investigator opinion',
    'CORRECTIVE_MEASURE_JUSTIFICATION': 'Corrective Measure Justification',
    'CORRECTIVE_MEASURE_MSC_CONSULTATION': 'Corrective measure MSC consultation',
    'CORRECTIVE_MEASURE_REQUEST': 'Corrective Measure Request Opinion',
    'CORRECTIVE_MEASURE_REVERT_JUSTIFICATION': 'Corrective measure revert justification',
    'CORRECTIVE_MEASURE_SPONSOR_OPINION': 'Corrective measure Sponsor Opinion',
    'COVER_LETTER': 'Cover letter',
    'DATA_SAFETY_MONITORING_BOARD_CHARTER': 'Data Safety Monitoring Board Charter',
    'DESCRIPTION_OF_MODIFICATION': 'Modification Description',
    'FINANCIAL_ARRANGEMENTS': 'Financial arrangements',
    'FOLLOW_UP_MEASURES': 'Follow up measures',
    'INSPECTION_REPORT': 'Inspection report',
    'INSPECTION_REPORT_THIRD_COUNTRY_INSPECTORATE': 'Inspection report: Third country inspectorate',
    'INVESTIGATIONAL_MEDICAL_PRODUCT_DOSSIER_SAFETY_AND_EFFICACY': 'Investigational Medicinal Product Dossier: Safety and Efficacy',
    'INVESTIGATOR_BROCHURE': 'Investigator Brochure',
    'INVESTIGATOR_CURRICULUM_VITAE': 'Investigator CV',
    'JOINT_CONTROLLERSHIP_AGREEMENT': 'Joint Controllership Agreement',
    'LAYPERSONS_SUMMARY_OF_RESULTS': 'Laypersons summary of results',
    'LIST_OF_CHANGES': 'List of Changes',
    'LOW_INTERVENTION_JUSTIFICATION': 'Low Intervention Justification',
    'MSC_ADDITIONAL_INFORMATION_ASSESSMENT_DISCUSION_REQUEST': 'MSC Additional Information Assessment Discussion Request',
    'PARR1_SECTION_4_CLINICAL_ASSESSMENT_DRAFT': 'Part I Section 4 Clinical Assessment - Draft',
    'PARR1_SECTION_5_STATISTICAL_METHOLOGICAL_ASSESSMENT_DRAFT': 'Part I Section 5 Statistical Methodological Assessment - Draft',
    'PARR1_SECTION_6_REGULATORY_ASSESSMENT_DRAFT': 'Part I Section 6 Regulatory Assessment - Draft',
    'PARR1_SECTION_7_CONCLUSION_DRAFT': 'Part I Section 7 Conclusion - Draft',
    'PART1_ASSESSMENT_REPORT_EXCEPT_QUALITY_FINAL': 'Part I assessment report except quality - Final',
    'PART1_DISAGREEMENT_JUSTIFICATION': 'Part I Disagreement Justification',
    'PART1_INTENDED_DISAGREEMENT_JUSTIFICATION': 'Part I Intended Disagreement Justification',
    'PART1_SECTION_1_INTRODUCTION_DRAFT': 'Part I Section 1 Introduction - Draft',
    'PART1_SECTION_3_PRE_CLINICAL_ASSESSMENT_DRAFT': 'Part I Section 3 Pre clinical Assessment - Draft',
    'PART2_ASSESSMENT_REPORT_DRAFT': 'Part II assessment report - Draft',
    'PART2_ASSESSMENT_REPORT_FINAL': 'Part II Assessment Report - Final',
    'PIP_OPINION': 'PIP opinion',
    'PLAN_PROGRAMME_FOR_UNION_CONTROLS_FOR_MEMBER_STATES': 'Plan/Programme for Union controls for Member States',
    'PRIVACY_STATMENT': 'Privacy Statement',
    'PROOF_OF_INSURANCE': 'Proof of insurance',
    'PROOF_OF_PAYMENT': 'Proof of payment',
    'PROTOCOL': 'Protocol',
    'RECRUITMENT_ARRANGEMENTS': 'Recruitment arrangements',
    'REVERT_DECISION_SUPPORTING_DOCUMENTATION': 'Revert Decision Supporting documentation',
    'SERIOUS_BREACH_REPORT': 'Serious breach report',
    'SIMPLIFIED_INVESTIGATIONAL_MEDICAL_PRODUCT_DOSSIER_SAFETY_EFFICACY': 'Simplified IMPD: Safety and Efficacy',
    'SPONSOR_DISCUSSION_RESPONSE_SUPPORTING_DOCUMENT': 'Sponsor discussion response supporting document',
    'STUDY_DESIGN': 'Study design',
    'SUBJECT_INFORMATION_AND_INFORMED_CONSENT_FORM': 'Subject information and informed consent form',
    'SUITABILITY_OF_THE_CLINICAL_TRIAL_SITES_FACILITIES': 'Suitability of the clinical trial sites facilities',
    'SUITABILITY_OF_THE_INVESTIGATOR': 'Suitability of the investigator',
    'SUMMARY_ATTACHMENT': 'Summary attachment',
    'SUMMARY_OF_ASSESSMENT_AND_OUTCOME': 'Summary of Assessment and Outcome',
    'SUMMARY_OF_PRODUCT_CHARACTERISTICS': 'Summary of Product Characteristics (SmPC)',
    'SUMMARY_OF_RESULTS': 'Summary of results',
    'SUMMARY_OF_SCIENTIFIC_ADVICE': 'Summary of scientific advice',
    'SUMMARY_OF_SCIENTIFIC_ADVICE_REPORT': 'Summary of scientific advice report',
    'SUPPORTING_DOCUMENT': 'Supporting document from MS - Non Quality',
    'SUPPORTING_INFORMATION': 'Supporting information',
    'SUPPORTING_INFORMATION_WITHDRAW': 'Supporting information withdraw',
    'SYNOPSIS_OF_THE_PROTOCOL': 'Synopsis of the protocol',
    'UNEXPECTED_EVENT_REPORT': 'Unexpected event report',
    'UNION_CONTROL_REPORT': 'Union control report',
    'UNION_CONTROL_REPORT_SUPPORTING_DOCUMENTATION': 'Union Control Report Supporting documentation',
    'UNION_CONTROL_SUPPORTING_DOCUMENTATION': 'Union Control Supporting documentation',
    'URGENT_SAFETY_MEASURE_REPORT': 'Urgent safety measure report',
}
