# Generated by Django 4.1 on 2022-09-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20220720_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionform',
            name='is_new_medtech_law',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionform',
            name='medtech_ce_symbol',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionform',
            name='medtech_certified_for_exact_indications',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionform',
            name='medtech_certified_for_other_indications',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionform',
            name='medtech_manual_included',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionform',
            name='submission_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'monocentric'), (2, 'multicentric, main ethics commission'), (6, 'multicentric, local ethics commission')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='submissionform',
            name='substance_p_c_t_final_report',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionform',
            name='substance_p_c_t_gcp_rules',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionform',
            name='substance_preexisting_clinical_tries',
            field=models.BooleanField(blank=True, db_column='existing_tries', null=True),
        ),
    ]
