# Generated by Django 4.1 on 2022-09-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_submissionform_is_new_medtech_law_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionform',
            name='project_type_non_interventional_study_mpg',
            field=models.BooleanField(default=False),
        ),
    ]
