# Generated by Django 4.1.3 on 2022-11-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_submissionform_project_type_non_interventional_study_mpg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionform',
            name='submission_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'monocentric'), (2, 'multicentric, main ethics commission'), (6, 'multicentric, local ethics commission')], null=True),
        ),
    ]
