# Generated by Django 4.1.3 on 2022-11-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_submissionform_remove_null_for_string_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionform',
            name='study_plan_statalgorithm',
            field=models.CharField(max_length=160),
        ),
    ]
