# Generated by Django 4.1.3 on 2023-01-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_submissionform_study_plan_statalgorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionform',
            name='subject_maxage_unit',
            field=models.SmallIntegerField(choices=[(1, 'hours'), (2, 'days'), (3, 'months'), (4, 'years')], default=4),
        ),
        migrations.AddField(
            model_name='submissionform',
            name='subject_minage_unit',
            field=models.SmallIntegerField(choices=[(1, 'hours'), (2, 'days'), (3, 'months'), (4, 'years')], default=4),
        ),
        migrations.AlterField(
            model_name='submissionform',
            name='subject_maxage',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='submissionform',
            name='subject_minage',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.RunSQL('''
            UPDATE core_submissionform SET subject_maxage_unit = 4, subject_minage_unit = 4;
        ''')
    ]
