# Generated by Django 4.1.3 on 2023-01-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_submissionform_subject_maxage_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionform',
            name='subject_noncompetent_guarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submissionform',
            name='subject_noncompetent_minor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submissionform',
            name='subject_noncompetent_emergency_study',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submissionform',
            name='subject_noncompetent_unconscious',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL('''
            UPDATE core_submissionform
            SET subject_noncompetent_guarded         = true,
                subject_noncompetent_minor           = true,
                subject_noncompetent_emergency_study = true,
                subject_noncompetent_unconscious     = true
            WHERE subject_noncompetents = true;
        '''),
        migrations.RemoveField(
            model_name='submissionform',
            name='subject_noncompetents',
        ),
    ]
