# Generated by Django 4.1.3 on 2023-02-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_submissionform_german_dataaccess_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionform',
            name='subject_divers',
            field=models.BooleanField(default=False),
        ),
    ]
