# Generated by Django 4.1.3 on 2023-02-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_submissionform_subject_divers'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionform',
            name='sponsor_country_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
