# Generated by Django 4.1.3 on 2023-02-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_submissionform_sponsor_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigator',
            name='contact_suffix_title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submissionform',
            name='invoice_contact_suffix_title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submissionform',
            name='sponsor_contact_suffix_title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submissionform',
            name='submitter_contact_suffix_title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
