# Generated by Django 4.1.3 on 2023-02-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_investigator_contact_suffix_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionform',
            name='submitter_phone_number',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
