# Generated by Django 4.1.3 on 2023-02-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_submissionform_submitter_is_authorized_by_sponsor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionform',
            name='non_applicant_submitter_contact_first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submissionform',
            name='non_applicant_submitter_contact_gender',
            field=models.CharField(blank=True, choices=[('f', 'Ms'), ('m', 'Mr')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='submissionform',
            name='non_applicant_submitter_contact_last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submissionform',
            name='non_applicant_submitter_contact_suffix_title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submissionform',
            name='non_applicant_submitter_contact_title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submissionform',
            name='non_applicant_submitter_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='submissionform',
            name='non_applicant_submitter_jobtitle',
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AddField(
            model_name='submissionform',
            name='non_applicant_submitter_organisation',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='submissionform',
            name='non_applicant_submitter_phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
