# Generated by Django 4.1.3 on 2023-02-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_submissionform_submitter_is_authorized_by_sponsor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionform',
            name='insurance_submit_later',
            field=models.BooleanField(default=False),
        ),
    ]
