# Generated by Django 4.1.3 on 2023-02-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_investigator_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigator',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
