# Generated by Django 4.1.3 on 2023-02-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_investigator_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigatoremployee',
            name='organisation',
            field=models.TextField(),
        ),
    ]
