# Generated by Django 4.1.3 on 2023-02-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_investigatoremployee_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionform',
            name='invoice_country_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
