# Generated by Django 4.1.3 on 2023-02-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_submissionform_invoice_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionform',
            name='sponsor_contact_first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='submissionform',
            name='sponsor_contact_gender',
            field=models.CharField(blank=True, choices=[('f', 'Ms'), ('m', 'Mr')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='submissionform',
            name='sponsor_contact_last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
