# Generated by Django 4.1.3 on 2023-02-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_submissionform_sponsor_contact_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigatoremployee',
            name='suffix_title',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
