# Generated by Django 4.1.3 on 2023-03-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_submissionform_medtech_eu_ct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigator',
            name='contact_gender',
            field=models.CharField(choices=[('f', 'Ms'), ('m', 'Mr'), ('d', 'Divers')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='submissionform',
            name='invoice_contact_gender',
            field=models.CharField(blank=True, choices=[('f', 'Ms'), ('m', 'Mr'), ('d', 'Divers')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='submissionform',
            name='sponsor_contact_gender',
            field=models.CharField(blank=True, choices=[('f', 'Ms'), ('m', 'Mr'), ('d', 'Divers')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='submissionform',
            name='submitter_contact_gender',
            field=models.CharField(choices=[('f', 'Ms'), ('m', 'Mr'), ('d', 'Divers')], max_length=1, null=True),
        ),
    ]
