# Generated by Django 4.1.3 on 2023-03-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_investigator_contact_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedsettings',
            name='warning_window_certificate',
            field=models.SmallIntegerField(choices=[(0, '1 Woche'), (1, '2 Wochen'), (2, '3 Wochen'), (3, '4 Wochen'), (4, '5 Wochen'), (5, '6 Wochen'), (6, '7 Wochen'), (7, '8 Wochen')], default=5),
        ),
    ]
