# Generated by Django 4.1.3 on 2023-03-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_advancedsettings_warning_window_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionform',
            name='project_type_medical_device_combination_studies',
            field=models.BooleanField(default=False),
        ),
    ]
