# Generated by Django 4.1.3 on 2023-03-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_submissionform_project_type_medical_device_combination_studies'),
    ]

    operations = [
        migrations.RunSQL('''
create or replace view core_mysubmission as
(
select distinct unnest(array [
    s.presenter_id, s.susar_presenter_id,
    sf.submitter_id, sf.sponsor_id, i.user_id
    ])               as user_id,
                s.id as submission_id
from core_submission s
         left join core_submissionform sf on sf.id = s.current_submission_form_id
         left join core_investigator i on i.submission_form_id = sf.id);
                '''),
    ]
