# Generated by Django 4.1.3 on 2023-05-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_include_all_investigators_in_my_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigatoremployee',
            name='sex',
            field=models.CharField(choices=[('m', 'Mr'), ('f', 'Ms'), ('d', 'Divers')], max_length=1),
        ),
    ]
