# Generated by Django 4.1.3 on 2023-03-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='clinics',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='core.clinic'),
        ),
    ]
