# Generated by Django 4.1.3 on 2023-05-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_investigatoremployee_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionform',
            name='subject_divers',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes'), (2, 'undefined')], default=2),
        ),
        migrations.AlterField(
            model_name='submissionform',
            name='subject_divers',
            field=models.SmallIntegerField(choices=[(0, 'no'), (1, 'yes'), (2, 'undefined')], default=2),
        ),
    ]
