# Generated by Django 4.1.3 on 2023-04-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_clinic_submission_clinics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigatoremployee',
            name='sex',
            field=models.CharField(choices=[('m', 'Mr'), ('f', 'Ms'), ('d', 'Divers')], max_length=1),
        ),
    ]
