# Generated by Django 4.1.3 on 2023-03-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_alter_submissionform_subject_divers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('deactivated', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='clinics',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='core.clinic'),
        ),
    ]
