# Generated by Django 4.1.3 on 2023-06-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_clinic_submission_clinics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionform',
            name='subject_divers',
            field=models.SmallIntegerField(choices=[(0, 'yes'), (1, 'no'), (2, 'undefined')], default=2),
        ),
    ]
