# Generated by Django 4.1.3 on 2023-07-05 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20170119_1048'),
        ('documents', '0005_remove_documenttype_helptext'),
        ('core', '0080_submission_ctis_transition'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('tasks', models.ManyToManyField(to='tasks.tasktype')),
            ],
        ),
    ]
