# Generated by Django 4.1.3 on 2023-07-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_submission_ctis_transition'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionform',
            name='subject_maxage_not_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submissionform',
            name='subject_maxage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionform',
            name='subject_maxage_unit',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'hours'), (2, 'days'), (3, 'months'), (4, 'years')], null=True),
        ),
    ]
