# Generated by Django 4.1.3 on 2023-11-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_supportingdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionform',
            name='is_withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
