# Generated by Django 4.1.3 on 2023-11-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0083_submissionform_is_withdrawn'), ('core', '0084_advancedsettings_display_amendment_in_meeting_for_board_member')]

    dependencies = [
        ('core', '0082_supportingdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionform',
            name='is_withdrawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advancedsettings',
            name='display_amendment_in_meeting_for_board_member',
            field=models.BooleanField(default=False),
        ),
    ]
