# Generated by Django 4.1.3 on 2024-03-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_submissionform_is_withdrawn_squashed_and_advancedsettings_display_amendment_in_meeting_for_board_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionform',
            name='sponsor_contact_first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='submissionform',
            name='sponsor_contact_last_name',
            field=models.CharField(max_length=30),
        ),
    ]
