# Generated by Django 4.1.3 on 2023-11-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_submissionform_is_withdrawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedsettings',
            name='display_amendment_in_meeting_for_board_member',
            field=models.BooleanField(default=False),
        ),
    ]
