# Generated by Django 4.1.3 on 2024-04-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_alter_submissionform_sponsor_contact_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedsettings',
            name='dont_delegate_specalist_tasks_from_executive',
            field=models.BooleanField(default=False),
        ),
    ]
