# Generated by Django 4.1.13 on 2024-12-04 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_advancedsettings_dont_delegate_specalist_tasks_from_executive'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTRSubmissionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.JSONField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.submission')),
            ],
        ),
    ]
