# Generated by Django 5.2.14 on 2026-07-15 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_advancedsettings_dont_delegate_specalist_tasks_from_executive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CTRSubmissionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.JSONField()),
                ('is_transient', models.BooleanField(default=False)),
                ('is_withdrawn', models.BooleanField(default=False)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('presenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presented_ctr_submission_forms', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctr_forms', to='core.submission')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='current_ctr_form',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_for_submission', to='core.ctrsubmissionform'),
        ),
    ]
