# Generated by Django 4.1.13 on 2024-12-04 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_ctrsubmissionform'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='current_ctr_form',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_ctr_for_submission', to='core.ctrsubmissionform'),
        ),
    ]
