# Generated by Django 5.2.14 on 2026-07-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_ctrsubmissionform_submission_current_ctr_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctrsubmissionform',
            name='ctis_base_number',
            field=models.CharField(db_index=True, default='', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctrsubmissionform',
            name='ctis_number',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctrsubmissionform',
            name='documents',
            field=models.JSONField(default=list),
        ),
    ]
