# Generated by Django 5.2.14 on 2026-08-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_submission_ctr_invited_trial_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedsettings',
            name='display_ctis_application_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advancedsettings',
            name='display_ctis_aut_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advancedsettings',
            name='display_ctis_eu_ct_number',
            field=models.BooleanField(default=False),
        ),
    ]
