# Generated by Django 5.2.14 on 2026-09-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_ctis_header_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='draft_assessment_report_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
