# Generated by Django 4.1.13 on 2024-06-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_documenttype_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_replacement_update',
            field=models.BooleanField(null=True),
        ),
    ]
