# Generated by Django 4.1.3 on 2023-03-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_userprofile_signing_connector'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='suffix_title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('f', 'Ms'), ('m', 'Mr'), ('d', 'Divers')], max_length=1),
        ),
    ]
