# Generated by Django 4.1.3 on 2023-12-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_userprofile_suffix_title_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='organisation',
            field=models.TextField(blank=True),
        ),
    ]
