# Generated by Django 5.2.14 on 2026-05-20 13:54

from django.db import migrations, models


def create_missing_usersettings(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserSettings = apps.get_model('users', 'UserSettings')
    existing = set(UserSettings.objects.values_list('user_id', flat=True))
    UserSettings.objects.bulk_create([
        UserSettings(user=user)
        for user in User.objects.exclude(pk__in=existing)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_userprofile_communication_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='submission_filter_all',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='submission_filter_assigned',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='submission_filter_mine',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='submission_filter_search',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='submission_filter_widget',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='submission_filter_widget_internal',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='useradministration_filter',
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(create_missing_usersettings, migrations.RunPython.noop),
    ]
