# Generated by Django 5.2.14 on 2026-09-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_usersettings_submission_filter_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='ctis_overview_filter',
            field=models.JSONField(default=dict),
        ),
    ]
