# Generated by Django 2.0 on 2022-06-24 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20170119_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='nodetype_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflow.NodeType'),
        ),
    ]
