# Generated by Django 4.1 on 2022-09-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0009_auto_20220810_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistanswer',
            name='answer',
            field=models.BooleanField(null=True),
        ),
    ]
