# Generated by Django 4.1.3 on 2023-04-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0010_alter_checklistanswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('completed', 'Completed'), ('review_ok', 'Review OK'), ('review_ok_internal', 'Review OK internal'), ('review_fail', 'Review Failed'), ('dropped', 'Dropped')], default='new', max_length=18),
        ),
    ]
