# Generated by Django 4.1.3 on 2023-03-15 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_documenttype_helptext'),
        ('core', '0075_clinic_submission_clinics'),
        ('meetings', '0011_auto_20170207_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingClinicProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_sent_at', models.DateTimeField(null=True)),
                ('protocol_rendering_started_at', models.DateTimeField(null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_protocols', to='core.clinic')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_protocols', to='meetings.meeting')),
                ('protocol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
            ],
        ),
    ]
