# Generated by Django 4.1.3 on 2023-03-22 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0012_meetingsubmissionprotocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='board_members',
            field=models.ManyToManyField(related_name='included_in_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
