# Generated by Django 4.1.3 on 2023-03-27 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0013_meeting_board_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='invited_groups',
            field=models.ManyToManyField(related_name='invited_to_meetings', to='auth.group'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='invited_users',
            field=models.ManyToManyField(related_name='invited_to_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
