# Generated by Django 4.1.3 on 2023-05-22 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0005_remove_documenttype_helptext'),
        ('meetings', '0014_meeting_invited_groups_meeting_invited_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='documents',
            field=models.ManyToManyField(through='meetings.MeetingDocument', to='documents.document'),
        ),
    ]
