# Generated by Django 4.1.3 on 2023-05-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_documenttype_helptext'),
        ('meetings', '0014_meeting_invited_groups_meeting_invited_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='documents',
            field=models.ManyToManyField(related_name='related_meeting_documents', to='documents.document'),
        ),
    ]
