# Generated by Django 4.1.3 on 2023-07-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0015_meetingdocument_meeting_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingdocument',
            name='board_member_insight',
            field=models.BooleanField(default=False),
        ),
    ]
