# Generated by Django 4.1.3 on 2023-10-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0016_meetingdocument_board_member_insight'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_link',
            field=models.URLField(default=''),
        ),
    ]
