# Generated by Django 4.1.13 on 2024-07-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0017_meeting_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='ctr_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
