# Generated by Django 4.1.3 on 2024-04-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docstash', '0013_migrate_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='docstash',
            name='preview_generated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
