# Generated by Django 5.2.14 on 2026-05-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docstash', '0014_docstash_preview_generated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docstash',
            name='value',
            field=models.JSONField(default=dict),
        ),
    ]
