# Generated by Django 4.1.3 on 2023-11-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_ctistransitionnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationanswer',
            name='is_withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
